export const SELECT_POKEMON_FOR_MODAL = "SELECT_POKEMON_FOR_MODAL";
export const UNSELECT_POKEMON_FOR_MODAL = "UNSELECT_POKEMON_FOR_MODAL";
export const ADD_POKEMON_TO_FAVORITES = "ADD_POKEMON_TO_FAVORITES";
export const REMOVE_POKEMON_FROM_FAVORITES = "REMOVE_POKEMON_FROM_FAVORITES";
